In [1]:
library(Seurat)
library(tidyverse)

The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)

Attaching SeuratObject

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
humanMarkers.colon_polyps.stem.ensg <- c("ENSG00000165078", "ENSG00000139292", "ENSG00000140807", "ENSG00000112562", "ENSG00000183579")
humanMarkers.colon_polyps.goblet.ensg <- c("ENSG00000064787", "ENSG00000275395", "ENSG00000214814", "ENSG00000156049", "ENSG00000198788")

mouseMarkers.stomach_goblet <- c("Tff3", "Agr2", "Fcgbp", "Spink4", "Muc2")
humanMarkers.stomach_goblet <- c("TFF3", "SPINK4", "REG4", "FCGBP", "MUC2")

mouseMarkers.pancreas_acinar <- c("Cela2a", "Rnase1", "Zg16", "Cpa1", "Try4")
humanMarkers.pancreas_acinar <- c("PNLIPRP1", "PRSS1", "CELA3A", "RBPJL", "GP2")

# Tosti, L. et al., Gastroenterology 2021

In [2]:
tosti.cp <- readRDS("./data/rdsFiles/tosti_pancreas.epi.chronic_pancreatitis.rds")

tosti.cp
dim(tosti.cp@meta.data)
head(tosti.cp@meta.data)

An object of class Seurat
26782 features across 1161 samples within 2 assays
Active assay: RNA (24782 features, 0 variable features)
 1 other assay present: integrated
 1 dimensional reduction calculated: umap

[1] 1161   11

                   orig.ident   nCount_RNA nFeature_RNA percent.mt sample_ID
AAACGAACACTCATAG_1 pancreatitis  8928      4183         0.6720430  TUM_CP1
AAACGAAGTATTCTCT_1 pancreatitis 11008      4826         2.4345930  TUM_CP1
AAACGAAGTTCTTAGG_1 pancreatitis 13008      4386         0.5381304  TUM_CP1
AAACGAAGTTGCGTAT_1 pancreatitis  4423      2372         0.6104454  TUM_CP1
AAACGAATCAAGAATG_1 pancreatitis  9526      4010         1.0392610  TUM_CP1
AAAGAACCACTCACTC_1 pancreatitis  8710      4231         2.0206659  TUM_CP1
                   Cluster       patient_ID sex  age hla.acinar    ann.epi
AAACGAACACTCATAG_1 Ductal        TUM_CP1    male 71  Ductal        Epithelial
AAACGAAGTATTCTCT_1 MUC5B+ Ductal TUM_CP1    male 71  MUC5B+ Ductal Epithelial
AAACGAAGTTCTTAGG_1 Beta          TUM_CP1    male 71  Beta          Epithelial
AAACGAAGTTGCGTAT_1 Tuft          TUM_CP1    male 71  Tuft          Epithelial
AAACGAATCAAGAATG_1 Beta          TUM_CP1    male 71  Beta          Epithelial
AAAGAACCACTCACTC_1 MUC5B+ Ductal TUM_CP1    male 71  MUC5B+ Ductal Epithelial

In [22]:
print(all(humanMarkers.stomach_goblet %in% rownames(tosti.cp)))
print(humanMarkers.stomach_goblet[!humanMarkers.stomach_goblet %in% rownames(tosti.cp)])

print(all(humanMarkers.pancreas_acinar %in% rownames(tosti.cp)))
print(humanMarkers.pancreas_acinar[!humanMarkers.pancreas_acinar %in% rownames(tosti.cp)])

[1] FALSE
[1] "MUC2"
[1] TRUE
character(0)

In [23]:
tosti.cp <- AddModuleScore(object = tosti.cp, 
                             features = list(humanMarkers.pancreas_acinar, humanMarkers.stomach_goblet), 
                             name = c("humanMarkers.pancreas_acinar", "humanMarkers.stomach_goblet"))

tosti.cp@meta.data <- tosti.cp@meta.data |>
    rename("humanMarkers.pancreas_acinar" = "humanMarkers.pancreas_acinar1", 
           "humanMarkers.stomach_goblet" = "humanMarkers.stomach_goblet2")
head(tosti.cp@meta.data)

Warning message:
“The following features are not present in the object: MUC2, not searching for symbol synonyms”

                   orig.ident   nCount_RNA nFeature_RNA percent.mt sample_ID
AAACGAACACTCATAG_1 pancreatitis  8928      4183         0.6720430  TUM_CP1
AAACGAAGTATTCTCT_1 pancreatitis 11008      4826         2.4345930  TUM_CP1
AAACGAAGTTCTTAGG_1 pancreatitis 13008      4386         0.5381304  TUM_CP1
AAACGAAGTTGCGTAT_1 pancreatitis  4423      2372         0.6104454  TUM_CP1
AAACGAATCAAGAATG_1 pancreatitis  9526      4010         1.0392610  TUM_CP1
AAAGAACCACTCACTC_1 pancreatitis  8710      4231         2.0206659  TUM_CP1
                   Cluster       patient_ID sex  age hla.acinar    ann.epi
AAACGAACACTCATAG_1 Ductal        TUM_CP1    male 71  Ductal        Epithelial
AAACGAAGTATTCTCT_1 MUC5B+ Ductal TUM_CP1    male 71  MUC5B+ Ductal Epithelial
AAACGAAGTTCTTAGG_1 Beta          TUM_CP1    male 71  Beta          Epithelial
AAACGAAGTTGCGTAT_1 Tuft          TUM_CP1    male 71  Tuft          Epithelial
AAACGAATCAAGAATG_1 Beta          TUM_CP1    male 71  Beta          Epithelial
AAAGAACCACTCACTC_1 MUC5B+ Ductal TUM_CP1    male 71  MUC5B+ Ductal Epithelial
                   humanMarkers.pancreas_acinar humanMarkers.stomach_goblet
AAACGAACACTCATAG_1 -0.39388247                  -0.009794140
AAACGAAGTATTCTCT_1 -0.32572252                  -0.024258857
AAACGAAGTTCTTAGG_1 -0.08643434                  -0.077529364
AAACGAAGTTGCGTAT_1 -0.08257147                  -0.307020451
AAACGAATCAAGAATG_1 -0.46408301                  -0.008451394
AAAGAACCACTCACTC_1 -0.23525638                   0.191060892

In [33]:
saveRDS(tosti.cp, "./data/rdsFiles/tosti_pancreas.epi.chronic_pancreatitis.rds")

# Ma, Z. et al., Gastroenterology 2022

In [3]:
ma.pinjury <- readRDS("./data/rdsFiles/ma_pancreas_injury.yfpPositive.rds")

ma.pinjury
dim(ma.pinjury@meta.data)
head(ma.pinjury@meta.data)

An object of class Seurat
32288 features across 13362 samples within 1 assay
Active assay: RNA (32288 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

[1] 13362     6

                            orig.ident    nCount_RNA nFeature_RNA clusters
AAACCCACACTCACTC.2wks.A8324 SeuratProject 16196      4794         11
AAACCCACAGGCATTT.2wks.A8324 SeuratProject 47452      6743          2
AAACCCAGTGAGTTTC.2wks.A8324 SeuratProject 22929      5617         10
AAACCCATCCTTATAC.2wks.A8324 SeuratProject  9305      1419          0
AAACCCATCGCTCCTA.2wks.A8324 SeuratProject 29731      5101          2
AAACGAACAGGAAGTC.2wks.A8324 SeuratProject 66120      7282          2
                            celltypeLabel cellBarcode
AAACCCACACTCACTC.2wks.A8324 EEC           AAACCCACACTCACTC-2wks-A8324
AAACCCACAGGCATTT.2wks.A8324 MucinDuctal   AAACCCACAGGCATTT-2wks-A8324
AAACCCAGTGAGTTTC.2wks.A8324 Tuft          AAACCCAGTGAGTTTC-2wks-A8324
AAACCCATCCTTATAC.2wks.A8324 Acinar        AAACCCATCCTTATAC-2wks-A8324
AAACCCATCGCTCCTA.2wks.A8324 MucinDuctal   AAACCCATCGCTCCTA-2wks-A8324
AAACGAACAGGAAGTC.2wks.A8324 MucinDuctal   AAACGAACAGGAAGTC-2wks-A8324

In [21]:
print(all(mouseMarkers.stomach_goblet %in% rownames(ma.pinjury)))
print(mouseMarkers.stomach_goblet[!mouseMarkers.stomach_goblet %in% rownames(ma.pinjury)])

print(all(mouseMarkers.pancreas_acinar %in% rownames(ma.pinjury)))
print(mouseMarkers.pancreas_acinar[!mouseMarkers.pancreas_acinar %in% rownames(ma.pinjury)])

[1] TRUE
character(0)
[1] TRUE
character(0)

In [7]:
ma.pinjury <- AddModuleScore(object = ma.pinjury, 
                             features = list(mouseMarkers.pancreas_acinar, mouseMarkers.stomach_goblet), 
                             name = c("mouseMarkers.pancreas_acinar", "mouseMarkers.stomach_goblet"))

ma.pinjury@meta.data <- ma.pinjury@meta.data |>
    rename("mouseMarkers.pancreas_acinar" = "mouseMarkers.pancreas_acinar1", 
           "mouseMarkers.stomach_goblet" = "mouseMarkers.stomach_goblet2")
head(ma.pinjury@meta.data)

                            orig.ident    nCount_RNA nFeature_RNA clusters
AAACCCACACTCACTC.2wks.A8324 SeuratProject 16196      4794         11
AAACCCACAGGCATTT.2wks.A8324 SeuratProject 47452      6743          2
AAACCCAGTGAGTTTC.2wks.A8324 SeuratProject 22929      5617         10
AAACCCATCCTTATAC.2wks.A8324 SeuratProject  9305      1419          0
AAACCCATCGCTCCTA.2wks.A8324 SeuratProject 29731      5101          2
AAACGAACAGGAAGTC.2wks.A8324 SeuratProject 66120      7282          2
                            celltypeLabel cellBarcode
AAACCCACACTCACTC.2wks.A8324 EEC           AAACCCACACTCACTC-2wks-A8324
AAACCCACAGGCATTT.2wks.A8324 MucinDuctal   AAACCCACAGGCATTT-2wks-A8324
AAACCCAGTGAGTTTC.2wks.A8324 Tuft          AAACCCAGTGAGTTTC-2wks-A8324
AAACCCATCCTTATAC.2wks.A8324 Acinar        AAACCCATCCTTATAC-2wks-A8324
AAACCCATCGCTCCTA.2wks.A8324 MucinDuctal   AAACCCATCGCTCCTA-2wks-A8324
AAACGAACAGGAAGTC.2wks.A8324 MucinDuctal   AAACGAACAGGAAGTC-2wks-A8324
                            mouseMarkers.pancreas_acinar
AAACCCACACTCACTC.2wks.A8324 -0.5193740
AAACCCACAGGCATTT.2wks.A8324 -0.5636725
AAACCCAGTGAGTTTC.2wks.A8324  0.2204598
AAACCCATCCTTATAC.2wks.A8324  3.7854557
AAACCCATCGCTCCTA.2wks.A8324 -0.3075051
AAACGAACAGGAAGTC.2wks.A8324 -0.7085076
                            mouseMarkers.stomach_goblet
AAACCCACACTCACTC.2wks.A8324 -0.3969829
AAACCCACAGGCATTT.2wks.A8324  0.5269775
AAACCCAGTGAGTTTC.2wks.A8324 -0.3865462
AAACCCATCCTTATAC.2wks.A8324 -0.2443634
AAACCCATCGCTCCTA.2wks.A8324  1.0477709
AAACGAACAGGAAGTC.2wks.A8324  0.9901325

In [32]:
saveRDS(ma.pinjury, "./data/rdsFiles/ma_pancreas_injury.yfpPositive.rds")

# Burdziak, C. et al., Science 2023

In [4]:
burdziak.pdac <- readRDS("./data/rdsFiles/burdziak_pdac_models.progressionCohort.rds")

burdziak.pdac
dim(burdziak.pdac@meta.data)
head(burdziak.pdac@meta.data)

An object of class Seurat
16826 features across 28131 samples within 1 assay
Active assay: RNA (16826 features, 0 variable features)
 2 dimensional reductions calculated: EMBED, PCA

[1] 28131     3

                                  batch             condition cluster
120703424252788_DACD394_Kate_plus DACD394_Kate_plus K1        0
120703436605797_DACD394_Kate_plus DACD394_Kate_plus K1        1
120703436909853_DACD394_Kate_plus DACD394_Kate_plus K1        1
120703454952236_DACD394_Kate_plus DACD394_Kate_plus K1        1
120726896892262_DACD394_Kate_plus DACD394_Kate_plus K1        5
120726897153838_DACD394_Kate_plus DACD394_Kate_plus K1        0

In [19]:
print(all(mouseMarkers.stomach_goblet %in% rownames(burdziak.pdac)))
print(mouseMarkers.stomach_goblet[!mouseMarkers.stomach_goblet %in% rownames(burdziak.pdac)])

print(all(mouseMarkers.pancreas_acinar %in% rownames(burdziak.pdac)))
print(mouseMarkers.pancreas_acinar[!mouseMarkers.pancreas_acinar %in% rownames(burdziak.pdac)])

[1] FALSE
[1] "Tff3"   "Agr2"   "Fcgbp"  "Spink4" "Muc2"
[1] FALSE
[1] "Cela2a" "Rnase1" "Zg16"   "Cpa1"   "Try4"

In [15]:
# We need to change the gene universe in this object to have gene symbols as uppercases
print(all(str_to_upper(mouseMarkers.stomach_goblet) %in% rownames(burdziak.pdac)))
print(str_to_upper(mouseMarkers.stomach_goblet)[!str_to_upper(mouseMarkers.stomach_goblet) %in% rownames(burdziak.pdac)])

print(all(str_to_upper(mouseMarkers.pancreas_acinar) %in% rownames(burdziak.pdac)))
print(str_to_upper(mouseMarkers.pancreas_acinar)[!str_to_upper(mouseMarkers.pancreas_acinar) %in% rownames(burdziak.pdac)])

[1] TRUE
character(0)
[1] TRUE
character(0)

In [16]:
burdziak.pdac <- AddModuleScore(object = burdziak.pdac, 
                                features = list(str_to_upper(mouseMarkers.pancreas_acinar), str_to_upper(mouseMarkers.stomach_goblet)), 
                                name = c("mouseMarkers.pancreas_acinar", "mouseMarkers.stomach_goblet"))

burdziak.pdac@meta.data <- burdziak.pdac@meta.data |>
    rename("mouseMarkers.pancreas_acinar" = "mouseMarkers.pancreas_acinar1", 
           "mouseMarkers.stomach_goblet" = "mouseMarkers.stomach_goblet2")
burdziak.pdac@meta.data

                                  batch             condition cluster
120703424252788_DACD394_Kate_plus DACD394_Kate_plus K1        0
120703436605797_DACD394_Kate_plus DACD394_Kate_plus K1        1
120703436909853_DACD394_Kate_plus DACD394_Kate_plus K1        1
120703454952236_DACD394_Kate_plus DACD394_Kate_plus K1        1
120726896892262_DACD394_Kate_plus DACD394_Kate_plus K1        5
120726897153838_DACD394_Kate_plus DACD394_Kate_plus K1        0
120726924409269_DACD394_Kate_plus DACD394_Kate_plus K1        3
120726924679596_DACD394_Kate_plus DACD394_Kate_plus K1        0
120726943616435_DACD394_Kate_plus DACD394_Kate_plus K1        1
120786758036718_DACD394_Kate_plus DACD394_Kate_plus K1        1
120786758584563_DACD394_Kate_plus DACD394_Kate_plus K1        1
120786772998966_DACD394_Kate_plus DACD394_Kate_plus K1        1
120786773294380_DACD394_Kate_plus DACD394_Kate_plus K1        0
120786785589598_DACD394_Kate_plus DACD394_Kate_plus K1        1
120864470322539_DACD394_Kate_plus DACD394_Kate_plus K1        1
120864484801955_DACD394_Kate_plus DACD394_Kate_plus K1        0
120864485005029_DACD394_Kate_plus DACD394_Kate_plus K1        3
120864497646003_DACD394_Kate_plus DACD394_Kate_plus K1        1
121202343041835_DACD394_Kate_plus DACD394_Kate_plus K1        1
121276801641269_DACD394_Kate_plus DACD394_Kate_plus K1        1
121276802166068_DACD394_Kate_plus DACD394_Kate_plus K1        1
121276815034670_DACD394_Kate_plus DACD394_Kate_plus K1        3
121276833848741_DACD394_Kate_plus DACD394_Kate_plus K1        5
121337991063387_DACD394_Kate_plus DACD394_Kate_plus K1        1
121338005146469_DACD394_Kate_plus DACD394_Kate_plus K1        1
121338005186846_DACD394_Kate_plus DACD394_Kate_plus K1        3
121338017733342_DACD394_Kate_plus DACD394_Kate_plus K1        1
121339869576491_DACD394_Kate_plus DACD394_Kate_plus K1        3
121339884267803_DACD394_Kate_plus DACD394_Kate_plus K1        0
121339884521373_DACD394_Kate_plus DACD394_Kate_plus K1        1
⋮                                 ⋮                 ⋮         ⋮
240498368239452_DACD550_kate_plus DACD550_kate_plus N1        2
240498383206244_DACD550_kate_plus DACD550_kate_plus N1        2
240498383402925_DACD550_kate_plus DACD550_kate_plus N1        2
240498383669021_DACD550_kate_plus DACD550_kate_plus N1        2
240498396322075_DACD550_kate_plus DACD550_kate_plus N1        2
240498414407011_DACD550_kate_plus DACD550_kate_plus N1        2
240617702677925_DACD550_kate_plus DACD550_kate_plus N1        2
240617703290723_DACD550_kate_plus DACD550_kate_plus N1        2
240617733967142_DACD550_kate_plus DACD550_kate_plus N1        2
240617734200052_DACD550_kate_plus DACD550_kate_plus N1        2
240634599500571_DACD550_kate_plus DACD550_kate_plus N1        2
240634614430443_DACD550_kate_plus DACD550_kate_plus N1        2
240634614475997_DACD550_kate_plus DACD550_kate_plus N1        2
240634626723230_DACD550_kate_plus DACD550_kate_plus N1        2
240634645625117_DACD550_kate_plus DACD550_kate_plus N1        2
241057653738923_DACD550_kate_plus DACD550_kate_plus N1        2
241057681033517_DACD550_kate_plus DACD550_kate_plus N1        2
241057700395827_DACD550_kate_plus DACD550_kate_plus N1        2
241098858818907_DACD550_kate_plus DACD550_kate_plus N1        2
241098858908531_DACD550_kate_plus DACD550_kate_plus N1        2
241098859104669_DACD550_kate_plus DACD550_kate_plus N1        9
241098873223606_DACD550_kate_plus DACD550_kate_plus N1        2
241098873256301_DACD550_kate_plus DACD550_kate_plus N1        2
241106375101299_DACD550_kate_plus DACD550_kate_plus N1        2
241106389429605_DACD550_kate_plus DACD550_kate_plus N1        2
241106402626286_DACD550_kate_plus DACD550_kate_plus N1        2
241114562127587_DACD550_kate_plus DACD550_kate_plus N1        2
241114576730845_DACD550_kate_plus DACD550_kate_plus N1        9
241114607893403_DACD550_kate_plus DACD550_kate_plus N1        2
241114608163612_DACD550_kate_plus DACD550_kate_plus N1        2
                                  mouseMarkers.pancreas_acinar
120703424252788_DACD394_Kate_plus -2.7694225
120703436605797_DACD394_Kate_plus -1.0813835
120703436909853_DACD394_Kate_plus -1.9626524
120703454952236_DACD394_Kate_plus -1.6521811
120726896892262_DACD394_Kate_plus -1.6916516
120726897153838_DACD394_Kate_plus -1.9432092
120726924409269_DACD394_Kate_plus  3.4148721
120726924679596_DACD394_Kate_plus -2.0782286
120726943616435_DACD394_Kate_plus -2.7782229
120786758036718_DACD394_Kate_plus -1.9965741
120786758584563_DACD394_Kate_plus -1.3410220
120786772998966_DACD394_Kate_plus -2.4128341
120786773294380_DACD394_Kate_plus -2.2083334
120786785589598_DACD394_Kate_plus -1.2036651
120864470322539_DACD394_Kate_plus -1.9507212
120864484801955_DACD394_Kate_plus -0.8977781
120864485005029_DACD394_Kate_plus  5.4934302
120864497646003_DACD394_Kate_plus -1.2796638
121202343041835_DACD394_Kate_plus -2.4129622
121276801641269_DACD394_Kate_plus -2.5406600
121276802166068_DACD394_Kate_plus -2.3982481
121276815034670_DACD394_Kate_plus  2.6556842
121276833848741_DACD394_Kate_plus -2.2940737
121337991063387_DACD394_Kate_plus -2.4019481
121338005146469_DACD394_Kate_plus -1.6973538
121338005186846_DACD394_Kate_plus  0.4465964
121338017733342_DACD394_Kate_plus -2.2005613
121339869576491_DACD394_Kate_plus  6.0100422
121339884267803_DACD394_Kate_plus -2.2505157
121339884521373_DACD394_Kate_plus -1.5104740
⋮                                 ⋮
240498368239452_DACD550_kate_plus  9.653243
240498383206244_DACD550_kate_plus 10.266319
240498383402925_DACD550_kate_plus 10.146777
240498383669021_DACD550_kate_plus 10.178690
240498396322075_DACD550_kate_plus 10.152779
240498414407011_DACD550_kate_plus 10.440936
240617702677925_DACD550_kate_plus 10.448858
240617703290723_DACD550_kate_plus 10.268531
240617733967142_DACD550_kate_plus 10.137674
240617734200052_DACD550_kate_plus 10.461048
240634599500571_DACD550_kate_plus 10.154613
240634614430443_DACD550_kate_plus  9.872619
240634614475997_DACD550_kate_plus 10.163729
240634626723230_DACD550_kate_plus 10.767573
240634645625117_DACD550_kate_plus  9.959438
241057653738923_DACD550_kate_plus 10.257107
241057681033517_DACD550_kate_plus 10.170075
241057700395827_DACD550_kate_plus 10.444750
241098858818907_DACD550_kate_plus 10.151168
241098858908531_DACD550_kate_plus 10.512591
241098859104669_DACD550_kate_plus  4.387385
241098873223606_DACD550_kate_plus  9.734189
241098873256301_DACD550_kate_plus 10.097088
241106375101299_DACD550_kate_plus  9.947735
241106389429605_DACD550_kate_plus 10.533157
241106402626286_DACD550_kate_plus 10.499744
241114562127587_DACD550_kate_plus 10.458093
241114576730845_DACD550_kate_plus  5.019289
241114607893403_DACD550_kate_plus 10.223884
241114608163612_DACD550_kate_plus 10.103774
                                  mouseMarkers.stomach_goblet
120703424252788_DACD394_Kate_plus  1.440895002
120703436605797_DACD394_Kate_plus -0.629677702
120703436909853_DACD394_Kate_plus -0.265274470
120703454952236_DACD394_Kate_plus -0.363092520
120726896892262_DACD394_Kate_plus -1.029222239
120726897153838_DACD394_Kate_plus  0.772819929
120726924409269_DACD394_Kate_plus -0.007626893
120726924679596_DACD394_Kate_plus  0.454381602
120726943616435_DACD394_Kate_plus -0.577349450
120786758036718_DACD394_Kate_plus -0.010017732
120786758584563_DACD394_Kate_plus -0.793913437
120786772998966_DACD394_Kate_plus -0.727388374
120786773294380_DACD394_Kate_plus  0.187785698
120786785589598_DACD394_Kate_plus -0.853643776
120864470322539_DACD394_Kate_plus -0.511321434
120864484801955_DACD394_Kate_plus -0.141017355
120864485005029_DACD394_Kate_plus -0.225303632
120864497646003_DACD394_Kate_plus -0.631152354
121202343041835_DACD394_Kate_plus -0.779178756
121276801641269_DACD394_Kate_plus -0.808064622
121276802166068_DACD394_Kate_plus -0.298908416
121276815034670_DACD394_Kate_plus  0.468149137
121276833848741_DACD394_Kate_plus -0.167370961
121337991063387_DACD394_Kate_plus -0.325923520
121338005146469_DACD394_Kate_plus -0.534997874
121338005186846_DACD394_Kate_plus -0.296048753
121338017733342_DACD394_Kate_plus  0.056964736
121339869576491_DACD394_Kate_plus  0.781246943
121339884267803_DACD394_Kate_plus  1.123800171
121339884521373_DACD394_Kate_plus -0.866146027
⋮                                 ⋮
240498368239452_DACD550_kate_plus -0.16142060
240498383206244_DACD550_kate_plus -0.07907877
240498383402925_DACD550_kate_plus -0.06813250
240498383669021_DACD550_kate_plus -0.09309532
240498396322075_DACD550_kate_plus -0.04181089
240498414407011_DACD550_kate_plus -0.07439685
240617702677925_DACD550_kate_plus -0.03899807
240617703290723_DACD550_kate_plus -0.03517656
240617733967142_DACD550_kate_plus -0.06805989
240617734200052_DACD550_kate_plus -0.05302626
240634599500571_DACD550_kate_plus -0.07439449
240634614430443_DACD550_kate_plus -0.06617138
240634614475997_DACD550_kate_plus -0.06358128
240634626723230_DACD550_kate_plus -0.03856141
240634645625117_DACD550_kate_plus  0.33552450
241057653738923_DACD550_kate_plus -0.03407827
241057681033517_DACD550_kate_plus -0.05653224
241057700395827_DACD550_kate_plus -0.03656720
241098858818907_DACD550_kate_plus -0.05506027
241098858908531_DACD550_kate_plus -0.05442527
241098859104669_DACD550_kate_plus -0.46472988
241098873223606_DACD550_kate_plus -0.04514629
241098873256301_DACD550_kate_plus  0.83585018
241106375101299_DACD550_kate_plus -0.06180188
241106389429605_DACD550_kate_plus -0.06439200
241106402626286_DACD550_kate_plus -0.03790320
241114562127587_DACD550_kate_plus -0.03763426
241114576730845_DACD550_kate_plus -0.47212026
241114607893403_DACD550_kate_plus -0.08576972
241114608163612_DACD550_kate_plus -0.03439570

In [31]:
saveRDS(burdziak.pdac, "./data/rdsFiles/burdziak_pdac_models.progressionCohort.rds")

# Chen, B. et al., Cell 2021

In [18]:
chen.dis_val <- readRDS("./data/rdsFiles/chen.precancer_crc_states.epi.dis_val.asc_ssc.rds")
chen.dis_val
dim(chen.dis_val@meta.data)
head(chen.dis_val@meta.data)

An object of class Seurat
34614 features across 19312 samples within 1 assay
Active assay: RNA (34614 features, 0 variable features)

[1] 19312    26

                          HTAN Parent Data File ID   HTAN Specimen ID
DIS_GACTTCTTCGATATGCAT-0  HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_GAACCACGCTACCTTGCC-0  HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_TGCCTCACGTGGAGCT-0    HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_TGAACTAGCCAGGAATAGA-0 HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_AGGGAACGAAGGCAACG-0   HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_AACCTGACAGCAGAAC-0    HTA11_3410_200000101113111 HTA11_3410_2000001011
                          Cell_Type Polyp_Type Sample_Classification
DIS_GACTTCTTCGATATGCAT-0  ASC       TA         AD
DIS_GAACCACGCTACCTTGCC-0  ASC       TA         AD
DIS_TGCCTCACGTGGAGCT-0    ASC       TA         AD
DIS_TGAACTAGCCAGGAATAGA-0 ASC       TA         AD
DIS_AGGGAACGAAGGCAACG-0   ASC       TA         AD
DIS_AACCTGACAGCAGAAC-0    ASC       TA         AD
                          cell_type_ontology_term_id disease_ontology_term_id
DIS_GACTTCTTCGATATGCAT-0  CL:0001063                 MONDO:0024660
DIS_GAACCACGCTACCTTGCC-0  CL:0001063                 MONDO:0024660
DIS_TGCCTCACGTGGAGCT-0    CL:0001063                 MONDO:0024660
DIS_TGAACTAGCCAGGAATAGA-0 CL:0001063                 MONDO:0024660
DIS_AGGGAACGAAGGCAACG-0   CL:0001063                 MONDO:0024660
DIS_AACCTGACAGCAGAAC-0    CL:0001063                 MONDO:0024660
                          donor_id   assay_ontology_term_id
DIS_GACTTCTTCGATATGCAT-0  HTA11_3410 EFO:0008913
DIS_GAACCACGCTACCTTGCC-0  HTA11_3410 EFO:0008913
DIS_TGCCTCACGTGGAGCT-0    HTA11_3410 EFO:0008913
DIS_TGAACTAGCCAGGAATAGA-0 HTA11_3410 EFO:0008913
DIS_AGGGAACGAAGGCAACG-0   HTA11_3410 EFO:0008913
DIS_AACCTGACAGCAGAAC-0    HTA11_3410 EFO:0008913
                          tissue_ontology_term_id ⋯ cell_type
DIS_GACTTCTTCGATATGCAT-0  UBERON:0001157          ⋯ neoplastic cell
DIS_GAACCACGCTACCTTGCC-0  UBERON:0001157          ⋯ neoplastic cell
DIS_TGCCTCACGTGGAGCT-0    UBERON:0001157          ⋯ neoplastic cell
DIS_TGAACTAGCCAGGAATAGA-0 UBERON:0001157          ⋯ neoplastic cell
DIS_AGGGAACGAAGGCAACG-0   UBERON:0001157          ⋯ neoplastic cell
DIS_AACCTGACAGCAGAAC-0    UBERON:0001157          ⋯ neoplastic cell
                          assay                      disease
DIS_GACTTCTTCGATATGCAT-0  single-cell RNA sequencing tubular adenoma
DIS_GAACCACGCTACCTTGCC-0  single-cell RNA sequencing tubular adenoma
DIS_TGCCTCACGTGGAGCT-0    single-cell RNA sequencing tubular adenoma
DIS_TGAACTAGCCAGGAATAGA-0 single-cell RNA sequencing tubular adenoma
DIS_AGGGAACGAAGGCAACG-0   single-cell RNA sequencing tubular adenoma
DIS_AACCTGACAGCAGAAC-0    single-cell RNA sequencing tubular adenoma
                          organism     sex  tissue
DIS_GACTTCTTCGATATGCAT-0  Homo sapiens male transverse colon
DIS_GAACCACGCTACCTTGCC-0  Homo sapiens male transverse colon
DIS_TGCCTCACGTGGAGCT-0    Homo sapiens male transverse colon
DIS_TGAACTAGCCAGGAATAGA-0 Homo sapiens male transverse colon
DIS_AGGGAACGAAGGCAACG-0   Homo sapiens male transverse colon
DIS_AACCTGACAGCAGAAC-0    Homo sapiens male transverse colon
                          self_reported_ethnicity development_stage
DIS_GACTTCTTCGATATGCAT-0  European                70-year-old human stage
DIS_GAACCACGCTACCTTGCC-0  European                70-year-old human stage
DIS_TGCCTCACGTGGAGCT-0    European                70-year-old human stage
DIS_TGAACTAGCCAGGAATAGA-0 European                70-year-old human stage
DIS_AGGGAACGAAGGCAACG-0   European                70-year-old human stage
DIS_AACCTGACAGCAGAAC-0    European                70-year-old human stage
                          nCount_RNA nFeature_RNA
DIS_GACTTCTTCGATATGCAT-0  13449      3174
DIS_GAACCACGCTACCTTGCC-0   3473      1227
DIS_TGCCTCACGTGGAGCT-0    10235      2465
DIS_TGAACTAGCCAGGAATAGA-0  8249      2701
DIS_AGGGAACGAAGGCAACG-0    3894      1353
DIS_AACCTGACAGCAGAAC-0     5330      1606

In [28]:
print(all(humanMarkers.colon_polyps.stem.ensg %in% rownames(chen.dis_val)))
print(humanMarkers.colon_polyps.stem.ensg[!humanMarkers.colon_polyps.stem.ensg %in% rownames(chen.dis_val)])

print(all(humanMarkers.colon_polyps.goblet.ensg %in% rownames(chen.dis_val)))
print(humanMarkers.colon_polyps.goblet.ensg[!humanMarkers.colon_polyps.goblet.ensg %in% rownames(chen.dis_val)])

[1] TRUE
character(0)
[1] TRUE
character(0)

In [29]:
chen.dis_val <- AddModuleScore(object = chen.dis_val, 
                             features = list(humanMarkers.colon_polyps.stem.ensg, humanMarkers.colon_polyps.goblet.ensg), 
                             name = c("humanMarkers.colon_polyps.stem.ensg","humanMarkers.colon_polyps.goblet.ensg"))

chen.dis_val@meta.data <- chen.dis_val@meta.data |>
    rename("humanMarkers.colon_polyps.stem.ensg" = "humanMarkers.colon_polyps.stem.ensg1", 
           "humanMarkers.colon_polyps.goblet.ensg" = "humanMarkers.colon_polyps.goblet.ensg2")
head(chen.dis_val@meta.data)

                          HTAN Parent Data File ID   HTAN Specimen ID
DIS_GACTTCTTCGATATGCAT-0  HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_GAACCACGCTACCTTGCC-0  HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_TGCCTCACGTGGAGCT-0    HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_TGAACTAGCCAGGAATAGA-0 HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_AGGGAACGAAGGCAACG-0   HTA11_3410_200000101113111 HTA11_3410_2000001011
DIS_AACCTGACAGCAGAAC-0    HTA11_3410_200000101113111 HTA11_3410_2000001011
                          Cell_Type Polyp_Type Sample_Classification
DIS_GACTTCTTCGATATGCAT-0  ASC       TA         AD
DIS_GAACCACGCTACCTTGCC-0  ASC       TA         AD
DIS_TGCCTCACGTGGAGCT-0    ASC       TA         AD
DIS_TGAACTAGCCAGGAATAGA-0 ASC       TA         AD
DIS_AGGGAACGAAGGCAACG-0   ASC       TA         AD
DIS_AACCTGACAGCAGAAC-0    ASC       TA         AD
                          cell_type_ontology_term_id disease_ontology_term_id
DIS_GACTTCTTCGATATGCAT-0  CL:0001063                 MONDO:0024660
DIS_GAACCACGCTACCTTGCC-0  CL:0001063                 MONDO:0024660
DIS_TGCCTCACGTGGAGCT-0    CL:0001063                 MONDO:0024660
DIS_TGAACTAGCCAGGAATAGA-0 CL:0001063                 MONDO:0024660
DIS_AGGGAACGAAGGCAACG-0   CL:0001063                 MONDO:0024660
DIS_AACCTGACAGCAGAAC-0    CL:0001063                 MONDO:0024660
                          donor_id   assay_ontology_term_id
DIS_GACTTCTTCGATATGCAT-0  HTA11_3410 EFO:0008913
DIS_GAACCACGCTACCTTGCC-0  HTA11_3410 EFO:0008913
DIS_TGCCTCACGTGGAGCT-0    HTA11_3410 EFO:0008913
DIS_TGAACTAGCCAGGAATAGA-0 HTA11_3410 EFO:0008913
DIS_AGGGAACGAAGGCAACG-0   HTA11_3410 EFO:0008913
DIS_AACCTGACAGCAGAAC-0    HTA11_3410 EFO:0008913
                          tissue_ontology_term_id ⋯ disease
DIS_GACTTCTTCGATATGCAT-0  UBERON:0001157          ⋯ tubular adenoma
DIS_GAACCACGCTACCTTGCC-0  UBERON:0001157          ⋯ tubular adenoma
DIS_TGCCTCACGTGGAGCT-0    UBERON:0001157          ⋯ tubular adenoma
DIS_TGAACTAGCCAGGAATAGA-0 UBERON:0001157          ⋯ tubular adenoma
DIS_AGGGAACGAAGGCAACG-0   UBERON:0001157          ⋯ tubular adenoma
DIS_AACCTGACAGCAGAAC-0    UBERON:0001157          ⋯ tubular adenoma
                          organism     sex  tissue
DIS_GACTTCTTCGATATGCAT-0  Homo sapiens male transverse colon
DIS_GAACCACGCTACCTTGCC-0  Homo sapiens male transverse colon
DIS_TGCCTCACGTGGAGCT-0    Homo sapiens male transverse colon
DIS_TGAACTAGCCAGGAATAGA-0 Homo sapiens male transverse colon
DIS_AGGGAACGAAGGCAACG-0   Homo sapiens male transverse colon
DIS_AACCTGACAGCAGAAC-0    Homo sapiens male transverse colon
                          self_reported_ethnicity development_stage
DIS_GACTTCTTCGATATGCAT-0  European                70-year-old human stage
DIS_GAACCACGCTACCTTGCC-0  European                70-year-old human stage
DIS_TGCCTCACGTGGAGCT-0    European                70-year-old human stage
DIS_TGAACTAGCCAGGAATAGA-0 European                70-year-old human stage
DIS_AGGGAACGAAGGCAACG-0   European                70-year-old human stage
DIS_AACCTGACAGCAGAAC-0    European                70-year-old human stage
                          nCount_RNA nFeature_RNA
DIS_GACTTCTTCGATATGCAT-0  13449      3174
DIS_GAACCACGCTACCTTGCC-0   3473      1227
DIS_TGCCTCACGTGGAGCT-0    10235      2465
DIS_TGAACTAGCCAGGAATAGA-0  8249      2701
DIS_AGGGAACGAAGGCAACG-0    3894      1353
DIS_AACCTGACAGCAGAAC-0     5330      1606
                          humanMarkers.colon_polyps.stem.ensg
DIS_GACTTCTTCGATATGCAT-0  -0.47939691
DIS_GAACCACGCTACCTTGCC-0  -0.02306254
DIS_TGCCTCACGTGGAGCT-0     0.11833286
DIS_TGAACTAGCCAGGAATAGA-0  0.05550029
DIS_AGGGAACGAAGGCAACG-0    0.08652106
DIS_AACCTGACAGCAGAAC-0     0.88706272
                          humanMarkers.colon_polyps.goblet.ensg
DIS_GACTTCTTCGATATGCAT-0  -0.5431514
DIS_GAACCACGCTACCTTGCC-0  -0.1664093
DIS_TGCCTCACGTGGAGCT-0    -0.4740813
DIS_TGAACTAGCCAGGAATAGA-0 -0.6648685
DIS_AGGGAACGAAGGCAACG-0   -0.5584206
DIS_AACCTGACAGCAGAAC-0    -0.3430571

In [30]:
saveRDS(chen.dis_val, "./data/rdsFiles/chen.precancer_crc_states.epi.dis_val.asc_ssc.rds")